### PR TITLE
Update Kotohogushi

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Review by Tymaeus — COMMENTED** [review]
Correction required:  Ryuun-Ohc's name should be rendered in the name tags as リューン＝オーク/Ryuun-Ohc, not 柳桜/Ryuuou (she is only given the name "Ryuuou" right before she ceases functioning and thus shouldn't be used as her nametag, リューン＝オーク is also how her name tag is displayed in the Switch version)

**Comment by DoctorDiablo** [comment]
> Correction required: Ryuun-Ohc's name should be rendered in the name tags as リューン＝オーク/Ryuun-Ohc, not 柳桜/Ryuuou (she is only given the name "Ryuuou" right before she ceases functioning and thus shouldn't be used as her name tag, リューン＝オーク is also how her name tag is displayed in the Switch version)

I'll double-check. These scripts are based on the ps3 version so the name probably displayed that way there, but if that's something they fixed on switch I can tweak it to match that.

**Comment by enumag** [comment]
it might be better to fix this in master branch and then rerun my script

**Comment by DoctorDiablo** [comment]
@Tymaeus Yeah looks like they did change it on switch.  They also changed Hanyuu's nametag to イェアソムール. I don't really want to read through the entire arc again just to see if there are any other differences between ps3 and switch. Is it safe to change these two nametags everywhere, and leave everything else the same?

**Comment by Tymaeus** [comment]
> @Tymaeus Yeah looks like they did change it on switch. They also changed Hanyuu's nametag to イェアソムール. I don't really want to read through the entire arc again just to see if there are any other differences between ps3 and switch. Is it safe to change these two nametags everywhere, and leave everything else the same?

That seems fine to me.

**Pull request merged**
