### PR TITLE
Translation corrections

### PR DESCRIPTION
**Pull request by Tymaeus**
Various translation corrections.

### CODE REVIEW

**Comment by Tymaeus** [comment]
I appear unable to access omot_026.txt at this current time, the message I see on the file page is "(Sorry about that, but we can’t show files that are this big right now.)" and attempting to edit the current commit just brings me to a blank file page. I would appreciate advice on how I can access it again.

**Comment by DoctorDiablo** [comment]
It's complaining there's a merge conflict. I need to figure out how to resolve that, and then it should work properly.

**Comment by msksk** [comment]
omot_026 is by far the longest in Mio Omote.
I don't know the exact limit, but at least "Sorry about that, but
... this big right now." is due to 026's file size or number of lines. I, too, couldn't edit 026 on github's website before, which displayed the same message. (and started to use github desktop and vscode)

By the way, I've already submitted 027's #484 before completing 026. So could you check 027 after my #484 gets merged, or review mine to prevent more conflicts? Thank you.



> I appear unable to access omot_026.txt at this current time, the message I see on the file page is "(Sorry about that, but we can’t show files that are this big right now.)" and attempting to edit the current commit just brings me to a blank file page. I would appreciate advice on how I can access it again.

**Comment by DoctorDiablo** [comment]
I'm going to just kill this pull request and then manually push these changes.  After you see another commit from me on this file you'll be good to continue.

**Pull request closed without merging**
