### PR TITLE
[WIP] Next release improvements

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by tellowkrinkle** [comment]
- [ ] Rename `GArc` local variable to `LConsoleArc` for compatibility with new DLLs

**Comment by enumag** [comment]
[ ] Add question about video opening

**Comment by DoctorDiablo** [comment]
- [ ] Changes references to `GHimatsubushiDay` in Yoigoshi scripts to use `GConsoleChoice`

**Comment by enumag** [comment]
[ ] Add new scenario images (see the main arcs for examples)
[ ] Add video openings and call them in the scripts

**Pull request merged**
